CREATE TABLE IF NOT EXISTS users (
    id SERIAL NOT NULL PRIMARY KEY,
    username CHARACTER VARYING(300) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS chats (
    id SERIAL NOT NULL PRIMARY KEY,
    name CHARACTER VARYING(300) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    id SERIAL NOT NULL PRIMARY KEY,
    chat_id INT NOT NULL,
    user_id INT NOT NULL,
    msg_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS userchat (
    user_id INT NOT NULL,
    chat_id INT NOT NULL
);
